# Name of workflow
name: CollectData
#Runs At 10:00 on everyday of May
on:
  push:
    branches:
      - master
  schedule:
    - cron: "* * * * *"   
    #Use https://crontab.guru/ for cron schedule expression

#steps to carry out 
jobs:
  build:
    # Create a ubuntu virtual machine
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content # checkout the repository content to github runner
        uses: actions/checkout@v2 
      
      - name: setup python   #install latest version of python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install dependencies    # install requirements to execute the script
        run: |
          pip install -r requirements.txt
      - name: execute py script   # run points_table.py to execute the script
        run: python points_table.py